server:
  port: 8083
  
spring:
  application:
    name: 'consultoriaseassessorias'
  datasource:
    url: jdbc:mysql://localhost:3306/contratos
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
     

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user      